part of '../index.dart';

/// Represents a local file
class LocalFile extends TdObject {
  LocalFile({
    this.path,
    this.canBeDownloaded = false,
    this.canBeDeleted = false,
    this.isDownloadingActive = false,
    this.isDownloadingCompleted = false,
    required this.downloadOffset,
    required this.downloadedPrefixSize,
    required this.downloadedSize,
  });

  /// Parse from a json
  factory LocalFile.fromJson(Map<String, dynamic> json) => LocalFile(
        path: json['path'],
        canBeDownloaded: json['can_be_downloaded'],
        canBeDeleted: json['can_be_deleted'],
        isDownloadingActive: json['is_downloading_active'],
        isDownloadingCompleted: json['is_downloading_completed'],
        downloadOffset: json['download_offset'],
        downloadedPrefixSize: json['downloaded_prefix_size'],
        downloadedSize: json['downloaded_size'],
      );

  static const CONSTRUCTOR = 'localFile';

  /// [canBeDeleted] True, if the file can be deleted
  bool canBeDeleted;

  /// [canBeDownloaded] True, if it is possible to try to download or generate the file
  bool canBeDownloaded;

  /// [downloadOffset] Download will be started from this offset. downloaded_prefix_size is calculated from this offset
  int downloadOffset;

  /// [downloadedPrefixSize] If is_downloading_completed is false, then only some prefix of the file starting from download_offset is ready to be read.
  /// downloaded_prefix_size is the size of that prefix
  int downloadedPrefixSize;

  /// [downloadedSize] Total downloaded file bytes. Should be used only for calculating download progress.
  /// The actual file size may be bigger, and some parts of it may contain garbage
  int downloadedSize;

  /// [isDownloadingActive] True, if the file is currently being downloaded (or a local copy is being generated by some other means)
  bool isDownloadingActive;

  /// [isDownloadingCompleted] True, if the local copy is fully available
  bool isDownloadingCompleted;

  /// [path] Local path to the locally available file part; may be empty
  String? path;

  @override
  String getConstructor() => CONSTRUCTOR;

  @override
  Map<String, dynamic> toJson() {
    return {
      "@type": CONSTRUCTOR,
      "path": this.path,
      "can_be_downloaded": this.canBeDownloaded,
      "can_be_deleted": this.canBeDeleted,
      "is_downloading_active": this.isDownloadingActive,
      "is_downloading_completed": this.isDownloadingCompleted,
      "download_offset": this.downloadOffset,
      "downloaded_prefix_size": this.downloadedPrefixSize,
      "downloaded_size": this.downloadedSize,
    };
  }
}
